### PR TITLE
Smbdirect v1

### PR DESCRIPTION
**Pull request by hclee**
This patch set implements SMB direct in CIFSD.                                  
                                                                                
The first 6 patches rework transport_tcp.c file. before                         
adding SMD direct as a new transport protocol. This                             
patches separate out Transport from Connection, and                             
make Connection send and receive SMB messages using                             
Transport operations.                                                           
                                                                                
The remaining patches implement SMB direct. This patches                        
establish RDMA connection with clients, and send/                               
receive SMB messages to/from clients using SMB direct                           
pacekts.                                                                        
                                                                                
In this patch set, CIFSD cannot process SMB READ/WRITE                          
requests, and have problem to map vmalloced response                            
buffers for DMA transfer. I am implementing these and                           
going to send patches.

### CODE REVIEW

**Comment by namjaejeon** [comment]
Hi Hyunchul,

First, thanks for your work!
please send the patches to linux-cifsd-devel mailing list also ^^

and travis-CI build test is stoppted by adding new configuration.
Need to add the following line to .travis.yml file.

- echo 'CONFIG_CIFSD_SMBDIRECT=n' >> .config

Thanks again!

**Comment by namjaejeon** [comment]
one more build error is coming.

  CC [M]  fs/cifsd/smb1pdu.o
[01m[Kfs/cifsd/smb1pdu.c:14:27:[m[K [01;31m[Kfatal error: [m[Ktransport_tcp.h: No such file or directory
compilation terminated.
scripts/Makefile.build:275: recipe for target 'fs/cifsd/smb1pdu.o' failed
make[1]: *** [fs/cifsd/smb1pdu.o] Error 1
Makefile:1722: recipe for target 'fs/cifsd/cifsd.o' failed
make: *** [fs/cifsd/cifsd.o] Error 2
travis_time:end:068dc5d3:start=1559720347859600424,finish=1559720375631126316,duration=27771525892
[0K[31;1mThe command "make fs/cifsd/cifsd.ko" exited with 2.[0m

Could you please check build with 4.1 kernel ?

Thanks!

**Comment by hclee** [comment]
> one more build error is coming.
> 
> CC [M] fs/cifsd/smb1pdu.o
> �[01m�[Kfs/cifsd/smb1pdu.c:14:27:�[m�[K �[01;31m�[Kfatal error: �[m�[Ktransport_tcp.h: No such file or directory
> compilation terminated.
> scripts/Makefile.build:275: recipe for target 'fs/cifsd/smb1pdu.o' failed
> make[1]: *** [fs/cifsd/smb1pdu.o] Error 1
> Makefile:1722: recipe for target 'fs/cifsd/cifsd.o' failed
> make: *** [fs/cifsd/cifsd.o] Error 2
> travis_timeend068dc5d3:start=1559720347859600424,finish=1559720375631126316,duration=27771525892
> �[0K�[31;1mThe command "make fs/cifsd/cifsd.ko" exited with 2.�[0m
> 
> Could you please check build with 4.1 kernel ?
> 
> Thanks!

Hi Namjae,

I will check this error. 

Thank you.

**Comment by hclee** [comment]
I did a pull request for v2. so I close this.

**Pull request closed without merging**
