### PR TITLE
cifsd: switch vfs to buffer_pool API

### PR DESCRIPTION
**Pull request by sergey-senozhatsky**
Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>

### CODE REVIEW

**Comment by sergey-senozhatsky** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled
> build or something wrong with the build itself. Check the details on how to adjust
> your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

Can we re-trigger this job? xfstest timeout has nothing to do with the commit in question.

-ss

**Comment by sergey-senozhatsky** [comment]
> 
> Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.197.195, 2604:1380:1:3600::1
> 
> Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.197.195|:443... failed: Connection timed out.
> 
> Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|2604:1380:1:3600::1|:443... failed: Network is unreachable.
> 
> The command "wget https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.1.36.tar.gz" failed and exited with 4 during .
> 


:(

**Comment by sergey-senozhatsky** [comment]
@namjaejeon could you re-start the job?

-ss

**Comment by namjaejeon** [comment]
Ah, I didn't notice your message. yep, I did restart now.
Thanks!

**Comment by sergey-senozhatsky** [comment]
It has failed because of 

```
generic/037 11s ... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

once again.

Can we get this merged?

-ss

**Comment by namjaejeon** [comment]
conflicting file => vfs.c, I think that it is better to add one more patch to run test by travis CI.

**Comment by sergey-senozhatsky** [comment]
screw this. really.

**Pull request closed without merging**
