### PR TITLE
Cifsd ss

### PR DESCRIPTION
**Pull request by sergey-senozhatsky**

### CODE REVIEW

**Comment by sergey-senozhatsky** [comment]
All tests failed with NO_MEMORY error... Even a simple SMB connect.

```
$ ./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.connect

smbtorture 4.10.6

Using seed 1566457469

time: 2019-08-22 07:04:29.686823

test: connect

time: 2019-08-22 07:04:29.687989

Failed to connect to SMB2 share \\127.0.0.1\cifsd-test3 - NT_STATUS_NO_MEMORY

time: 2019-08-22 07:04:29.688661

failure: connect [

../../source4/torture/smb2/connect.c:207: Expression `ok' failed: torture_smb2_connection failed

]

The command "./bin/smbtorture //127.0.0.1/cifsd-test3/ -Utestuser%1234 smb2.connect" exited with 1.
```

-ss

**Comment by namjaejeon** [comment]
cifsd: do not recompile smbtorture, Don't do that, we should use our samba. I modified samba testcase.

**Comment by namjaejeon** [comment]
I think that cifsd doesn't launch by kcifsd and cifsd mismatch. As you know, I added new parameters.

**Comment by sergey-senozhatsky** [comment]
> cifsd: do not recompile smbtorture, Don't do that, we should use our samba. I modified samba testcase.

ok.

**Comment by sergey-senozhatsky** [comment]
> I think that cifsd doesn't launch by kcifsd and cifsd mismatch. As you know, I added new parameters.

That testsuite is quite annoying at the memont.

**Pull request merged**
