### PR TITLE
Kernel 3 14 fixes

### PR DESCRIPTION
**Pull request by ahubchak**
Hello, currently I have finished porting cifsd-server for my needs.
It seem to be working properly with linux version 3.14.28.
Could you please have a look?

### CODE REVIEW

**Comment by neheb** [comment]
That's an interesting version to be running. Given that 3.16 is the oldest kernel supported upstream and this pull request adds support for it, looks good to me.

The second commit's message should be the same as the third, with the exception being the kernel version (3.19 from the looks of it).

**Comment by namjaejeon** [comment]
Hi Andrew,

We have currently supported from 4.1 version to the latest one.
If we apply this patch, We should support from kernel version under 4.1(3.14?).
We need the strong reason why we should support even though paying maintenance cost.
e.g. It will be used for great projects or products...

Thanks for your work!

**Comment by sergey-senozhatsky** [comment]
We generally want to have less of #LINUX_VERSION_CODE in the code. In fact, there
should be no #LINUX_VERSION_CODE at all by the time we send it out to LKML. The
more LINUX_VERSION_CODE we add now the more we will have to remove, sooner or
later.

So what can we do... We, probably, can mkdir a `contrib/` directory and put your patch there
as a patch file, say, under `linux-3.14-support.patch` name. So anyone who would want to
compile cifsd for 3.14 first would have to `patch -p1 < contrib/linux-3.14-support.patch` and
then compile cifsd.

-ss

**Comment by namjaejeon** [comment]
> So what can we do... We, probably, can mkdir a contrib/ directory and put your patch there
as a patch file, say, under linux-3.14-support.patch name. So anyone who would want to
compile cifsd for 3.14 first would have to patch -p1 < contrib/linux-3.14-support.patch and
then compile cifsd.

As the cifsd code is updated, patch hunk issue will eventually occur.

**Comment by sergey-senozhatsky** [comment]
> As the cifsd code is updated, patch hunk issue will eventually occur.

Sure, someone (not me) will have to keep an eye on that patch.

-ss

**Comment by ahubchak** [comment]
Hello all,

Thank you for your feedback. I was not sure if cifsd should support kernel versions older then 4.1 that is why this work was done. Currently, the project that I am working on is running on that version, so that is the reason of this work that was done. I just thought that it might be helpful to share it.

Also, I am not sure if supporting one patch (always to have a look to it) is a nice idea. IMHO it would be easier to specify in Readme of the project that only 4.1+ kernel versions are supported(I did not saw it there, maybe I just missed it :) ). And to attach a patch to this conversation, with a shared link somewhere for other needs.

Maybe that would be better.

Kind regards,
Andrew

**Comment by sergey-senozhatsky** [comment]
OK. So we can close this one right?

-ss

**Comment by namjaejeon** [comment]
Hi Andrew,

Yep, Agreed. I will update README.
If you have any issue while using cifsd, Let me know it.
Thanks for your work!

**Comment by ahubchak** [comment]
Yes, this pull-request can be closed.
Thank you for a review and your feedback.

**Pull request closed without merging**
